const config = {
    // apiUrl: 'https://findx-backend.onrender.com/api',
    apiUrl: 'https://findxserver-cqstechsolutions.vercel.app/api',

    gradients: {
        A: 'from-red-500 to-yellow-500',
        B: 'from-green-500 to-teal-400',
        C: 'from-blue-500 to-indigo-500',
        D: 'from-purple-500 to-pink-500',
        E: 'from-orange-500 to-red-400',
        F: 'from-cyan-500 to-blue-300',
        G: 'from-lime-500 to-green-400',
        H: 'from-indigo-400 to-purple-400',
        I: 'from-teal-400 to-emerald-400',
        J: 'from-amber-400 to-orange-500',
        K: 'from-sky-500 to-blue-600',
        L: 'from-rose-400 to-pink-600',
        M: 'from-violet-500 to-fuchsia-500',
        N: 'from-yellow-400 to-lime-500',
        O: 'from-pink-400 to-red-500',
        P: 'from-blue-400 to-cyan-400',
        Q: 'from-green-400 to-emerald-400',
        R: 'from-purple-600 to-indigo-600',
        S: 'from-teal-500 to-cyan-500',
        T: 'from-orange-400 to-amber-500',
        U: 'from-lime-400 to-green-500',
        V: 'from-indigo-500 to-blue-700',
        W: 'from-rose-500 to-red-400',
        X: 'from-fuchsia-500 to-pink-400',
        Y: 'from-emerald-500 to-teal-400',
        Z: 'from-red-400 to-rose-500',
    },

    companyIndustry: [
        'Accounting & Finance',
        'Administration & Office Support',
        'Advertising, Arts & Media',
        'Agriculture, Nature & Animal',
        'Architecture & Interior Design',
        'Banking & Financial Services',
        'Call Centre & Customer Service',
        'CEO & General Management',
        'Community Services & Development',
        'Construction',
        'Consulting & Strategy',
        'Design & Creative',
        'Education & Training',
        'Engineering',
        'Farming, Animals & Conservation',
        'Government & Defence',
        'Healthcare & Medical',
        'Hospitality & Tourism',
        'Human Resources & Recruitment',
        'Information & Communication Technology (ICT)',
        'Insurance & Superannuation',
        'Legal',
        'Logistics, Transport & Supply Chain',
        'Manufacturing, Production & Operations',
        'Marketing & Communications',
        'Media, Digital & Entertainment',
        'Mining, Resources & Energy',
        'Non-Profit & Volunteering',
        'Real Estate & Property',
        'Retail & Consumer Products',
        'Sales',
        'Science & Technology',
        'Security & Protective Services',
        'Sport & Recreation',
        'Trades & Services',
        'Transport & Rail',
        'Utilities & Energy',
        'Warehousing, Storage & Distribution',
        'Other / Miscellaneous',
    ],

    jobAdIndustries: {
        "Accounting": [
"Accounts Officers / Clerks",
"Accounts Payable",
"Accounts Receivable / Credit Control",
"Analysis & Reporting",
"Assistant Accountants",
"Audit -External",
"Audit -Internal",
"Bookkeeping & Small Practice",
"Accounting",
"Business Services & Corporate Advisory",
"Company Secretaries",
"Compliance & Risk",
"Cost",
"Accounting",
"Environmental",
"Accounting",
"Financial",
"Accounting & Reporting",
"Financial",
"Managers & Controllers",
"Forensic",
"Accounting & Investigation",
"Insolvency & Corporate",
"Recovery",
"Inventory & Fixed",
"Assets",
"Management",
"Management",
"Accounting & Budgeting",
"Payroll",
"Public",
"Sector",
"Accounting",
"Strategy & Planning",
"Sustainability",
"Reporting",
"Systems",
"Accounting & IT",
"Audit",
"Taxation",
"Treasury",
"Other",
],
"Administration & Office Support": [
"Administrative Assistants",
"Client & Sales Administration",
"Contracts Administration",
"Data Entry & Word Processing",
"Facilities Coordination",
"Office Coordination",
"Office Management",
"PA, EA & Secretarial",
"Receptionists",
"Records Management & Document",
"Control",
"Other",
],
"Advertising, Arts & Media": [
"Agency Account Management",
"Art Direction",
"Content Creation",
"Digital Media Production",
"Editing & Publishing",
"Event Management",
"Journalism & Writing",
"Management",
"Media Strategy, Planning & Buying",
"Performing Arts",
"Photography",
"Programming & Production",
"Promotions",
"Social Media Management",
"Other",
],
"Banking & Financial Services" : [
"Account & Relationship Management",
"Analysis & Reporting",
"Banking - Business",
"Banking - Corporate & Institutional",
"Banking - Retail/Branch",
"Client Services",
"Compliance & Risk",
"Corporate Finance & Investment",
"Banking",
"Credit",
"Financial Planning",
"Fintech Services",
"Funds Management",
"Management",
"Mortgages",
"Settlements",
"Stockbroking & Trading",
"Treasury",
"Wealth Management",
"Other",
],
"Call Centre & Customer Service": [
"Collections",
"Customer Experience Design",
"Customer Service - Call Centre",
"Customer Service - Customer Facing",
"Management & Support",
"Sales - Inbound",
"Sales - Outbound",
"Supervisors/Team Leaders",
"Technical Support",
"Other",
],
"CEO & General Management": [
"Board Appointments",
"CEO, COO & MD",
"Chief Innovation Officer",
"Chief Sustainability Officer",
"General/Business Unit Manager",
"Other",
],

"Community Services & Development": [
"Aged & Disability Support",
"Child Welfare, Youth & Family Services",
"Community Development",
"Community Health Promotion",
"Employment Services",
"Fundraising",
"Housing & Homelessness Services",
"Indigenous & Multicultural Services",
"Management",
"Social Enterprise Management",
"Volunteer Coordination & Support",
"Other",
],
"Construction": [
"Building Information Modeling (BIM)",
"Contracts Management",
"Estimating",
"Foreperson/Supervisors",
"Green Building & Sustainability",
"Health, Safety & Environment",
"Management",
"Planning & Scheduling",
"Plant & Machinery Operators",
"Project Management",
"Quality Assurance & Control",
"Surveying",
"Other",
],
"Consulting & Strategy": [
"Analysts",
"Corporate Development",
"Digital Transformation Consulting",
"Environment & Sustainability",
"Consulting",
"Innovation Strategy",
"Management & Change Consulting",
"Policy",
"Strategy & Planning",
"Other",
],

"Design & Architecture": [
"Architectural Drafting",
"Architecture",
"Experience Design (UX/UI)",
"Fashion & Textile Design",
"Graphic Design",
"Illustration & Animation",
"Industrial Design",
"Interior Design",
"Landscape Architecture",
"Sustainable Design",
"Urban Design & Planning",
"Web & Interaction Design",
"Other",
],
"Education & Training": [
"Childcare & Outside School Hours Care",
"Educational Technology",
"E-Learning Development",
"Library Services & Information",
"Management",
"Management - Schools",
"Management - Universities",
"Management - Vocational",
"Research & Fellowships",
"Student Services",
"Teaching - Early Childhood",
"Teaching - Primary",
"Teaching - Secondary",
"Teaching - Tertiary",
"Teaching - Vocational",
"Teaching Aides & Special Needs",
"Tutoring",
"Workplace Training & Assessment",
"Other",
],
"Engineering": [
"Aerospace Engineering",
"Automotive Engineering",
"Building Services Engineering",
"Chemical Engineering",
"Civil/Structural Engineering",
"Electrical/Electronic Engineering",
"Engineering Drafting",
"Environmental Engineering",
"Field Engineering",
"Industrial Engineering",
"Maintenance",
"Management",
"Materials Handling Engineering",
"Mechanical Engineering",
"Mechatronics Engineering",
"Process Engineering",
"Project Engineering",
"Project Management",
"Renewable Energy Engineering",
"Supervisors",
"Systems Engineering",
"Water & Waste Engineering",
"Other",
],
"Farming, Animals & Conservation": [
"AgriTech Development",
"Agronomy & Farm Services",
"Conservation, Parks & Wildlife",
"Farm Labour",
"Farm Management",
"Fishing & Aquaculture",
"Horticulture",
"Sustainable Agriculture",
"Veterinary Services & Animal Welfare",
"Winery & Viticulture",
"Other",
],
"Government & Defence": [
"Air Force",
"Army",
"Cybersecurity Policy",
],
"Emergency Services": [
"Government - Federal",
"Government - Local",
"Government - State",
"Navy",
"Police & Corrections",
"Policy, Planning & Regulation",
"Public Health Administration",
"Other",
],

"Healthcare & Medical": [
"Ambulance/Paramedics",
"Chiropractic & Osteopathic",
"Clinical/Medical Research",
"Dental",
"Dieticians",
"Environmental Services",
"General Practitioners",
"Health Informatics",
"Management",
"Medical Administration",
"Medical Imaging",
"Medical Specialists",
"Natural Therapies & Alternative Medicine",
"Nursing - A&E, Critical Care & ICU",
"Nursing - Aged Care",
"Nursing - Community, Maternal & Child",
"Health",
"Nursing - Educators & Facilitators",
"Nursing - General Medical & Surgical",
"Nursing - High Acuity",
"Nursing - Management",
"Nursing - Midwifery, Neo-Natal, SCN & NICU",
"Nursing - Paediatric & PICU",
"Nursing - Psych, Forensic & Correctional",
"Health",
"Nursing - Theatre & Recovery",
"Optical",
"Pathology",
"Pharmaceuticals & Medical Devices",
"Pharmacy",
"Physiotherapy, OT & Rehabilitation",
"Psychology, Counselling & Social Work",
"Residents & Registrars",
"Sales",
"Speech Therapy",
"Telehealth Services",
"Other",
],
"Hospitality & Tourism": [
"Airlines",
"Bar & Beverage Staff",
"Chefs/Cooks",
"Event Planning",
"Front Office & Guest Services",
"Gaming",
"Hospitality Technology",
"Housekeeping",
"Kitchen & Sandwich Hands",
"Management",
"Reservations",
"Tour Guides",
"Travel Agents/Consultants",
"Waiting Staff",
"Other",
],
"Human Resources & Recruitment": [
"Consulting & Generalist HR",
"HR Analytics",
"Industrial & Employee Relations",
"Management - Agency",
"Management - Internal",
"Occupational Health & Safety",
"Organisational Development",
"Recruitment - Agency",
"Recruitment - Internal",
"Remuneration & Benefits",
"Talent Acquisition Strategy",
"Training & Development",
"Other",
],
"Information & Communication": [
"Technology",
"Architects",
"Artificial Intelligence & Machine",
"Learning",
"Business/Systems Analysts",
"Cloud Computing",
"Computer Operators",
"Consultants",
"Cybersecurity",
"Database Development &",
"Administration",
"Developers/Programmers",
"Engineering - Hardware",
"Engineering - Network",
"Engineering - Software",
"Help Desk & IT Support",
"Management",
"Networks & Systems Administration",
"Product Management & Development",
"Programme & Project Management",
"Sales - Pre & Post",
"Security",
"Team Leaders",
"Technical Writing",
"Telecommunications",
"Testing & Quality Assurance",
"Web Development & Production",
"Other",
],
"Insurance & Superannuation": [
"Actuarial",
"Assessment",
"Brokerage",
"Claims",
"Compliance & Regulatory Affairs",
"Fund Administration",
"Insurance Technology (InsurTech)",
"Management",
"Risk Consulting",
"Superannuation",
"Underwriting",
"Workers' Compensation",
"Other",
],

"Legal": [
"Banking & Finance Law",
"Construction Law",
"Corporate & Commercial Law",
"Criminal & Civil Law",
"Environment & Planning Law",
"Family Law",
"Generalists - In-house",
"Generalists - Law Firm",
"Immigration Law",
"Industrial Relations & Employment Law",
"Insurance & Superannuation Law",
"Intellectual Property Law",
"Intellectual Property Law",
"Law Clerks & Paralegals",
"Legal Practice Management",
"Legal Secretaries",
"Litigation & Dispute Resolution",
"Personal Injury Law",
"Property Law",
"Tax Law",
"Technology & Privacy Law",
"Other",
],

"Manufacturing, Transport & Logistics" : [
"Analysis & Reporting",
"Assembly & Process Work",
"Automation & Robotics Operations",
"Aviation Services",
"Couriers, Drivers & Postal Services",
"Fleet Management",
"Freight/Cargo Forwarding",
"Import/Export & Customs",
"Machine Operators",
"Management",
"Pattern Makers & Garment Technicians",
"Pickers & Packers",
"Production, Planning & Scheduling",
"Public Transport & Taxi Services",
"Purchasing, Procurement & Inventory",
"Quality Assurance & Control",
"Rail & Maritime Transport",
"Road Transport",
"Supply Chain Analytics",
"Team Leaders/Supervisors",
"Warehousing, Storage & Distribution",
"Other",
],

"Marketing & Communications": [
"Brand Management",
"Digital & Search Marketing",
"Direct Marketing & CRM",
"Event Management",
"Growth Marketing",
"Influencer Marketing",
"Internal Communications",
"Management",
"Market Research & Analysis",
"Marketing Assistants/ Coordinators",
"Marketing Communications",
"Product Management & Development",
"Public Relations & Corporate Affairs",
"SEO/SEM Specialists",
"Trade Marketing",
"Other",
],

"Mining, Resources & Energy": [
"Analysis & Reporting",
"Health, Safety & Environment",
"Management",
"Mining - Drill & Blast",
"Mining - Engineering & Maintenance",
"Mining - Exploration & Geoscience",
"Mining - Operations",
"Mining - Processing",
"Mining Automation & Tech Integration",
"Natural Resources & Water",
"Oil & Gas - Drilling",
"Oil & Gas - Engineering & Maintenance",
"Oil & Gas - Exploration & Geoscience",
"Oil & Gas - Operations",
"Oil & Gas - Production & Refinement",
"Power Generation & Distribution",
"Renewable Energy Operations",
"Surveying",
"Other",
],

"Real Estate & Property" : [
"Administration",
"Analysts",
"Body Corporate & Facilities Management",
"Commercial Sales & Leasing",
"Commercial Sales, Leasing & Property",
"Management",
"PropTech & Digital Real Estate",
"Residential Leasing & Property Management",
"Residential Sales",
"Retail & Property Development",
"Valuation",
"Other",
],

"Retail & Consumer Products": [
"Buying",
"E-Commerce & Online Retail",
"Management - Area/ Multi-site",
"Management - Department/Assistant",
"Management - Store",
"Merchandisers",
"Omnichannel Retail Strategy",
"Planning",
"Retail Assistants",
"Other",
],

"Sales" : [
"Account & Relationship Management",
"Analysis & Reporting",
"Channel Sales",
"Management",
"New Business Development",
"SaaS Sales",
"Sales Coordinators",
"Sales Representatives/ Consultants",
"Territory Sales",
"Other",
],

"Science & Technology": [
"Biological & Biomedical Sciences",
"Biotechnology & Genetics",
"Chemistry & Physics",
"Clean Technology Research",
"Data Science",
"Environmental, Earth & Geosciences",
"Food Technology & Safety",
"Laboratory & Technical Services",
"Materials Sciences",
"Mathematics, Statistics & Information",
"Science",
"Modelling & Simulation",
"Quality Assurance & Control",
"Space & Astronomical Sciences",
"Other",
],

"Self Employment": [
"Business Opportunities",
"Coaching & Mentoring",
"Content Creator / Influencer",
"Franchising",
"Online Store Owner / E-commerce",
"Self Employment",
"Work From Home",
"Other",
],

"Sport & Recreation": [
"Coaching & Instruction",
"Fitness & Personal Training",
"Management",
"Recreation Program Management",
"Sports Science & Analytics",
"Other",
],

"Trades & Services" : [
"Air Conditioning & Refrigeration",
"Automotive Trades",
"Bakers & Pastry Chefs",
"Building Trades",
"Butchers",
"Carpentry & Cabinet Making",
"Cleaning Services",
"Electricians",
"EV Maintenance & Repair Services",
"Fitters, Turners & Machinists",
"Floristry",
"Gardening & Landscaping",
"Hair & Beauty Services",
"Labourers",
"Locksmiths",
"Maintenance & Handy person Services",
"Nannies & Babysitters",
"Painters & Sign Writers",
"Plumbers",
"Printing & Publishing Services",
"Security Services",
"Smart Home Installation",
"Tailors & Dressmakers",
"Technicians",
"Welders & Boilermakers",
"Other",
]
    },

    // Add category-based keyword mappings
    categoryKeywords: {
        "Accounting": [
            "Financial Analysis",
            "Bookkeeping",
            "Tax Preparation",
            "Audit",
            "Financial Reporting",
            "Budgeting",
            "Payroll",
            "Compliance",
            "Financial Planning",
            "Cost Accounting",
            "Accounts Payable",
            "Accounts Receivable",
            "General Ledger",
            "Financial Statements",
            "Cash Flow Management",
            "Internal Controls",
            "Risk Assessment",
            "Forensic Accounting",
            "Management Accounting",
            "Financial Modeling"
        ],
        "Administration & Office Support": [
            "Office Management",
            "Administrative Support",
            "Data Entry",
            "Executive Assistant",
            "Office Coordination",
            "Records Management",
            "Customer Service",
            "Project Coordination",
            "Document Management",
            "Business Administration",
            "Calendar Management",
            "Travel Coordination",
            "Meeting Planning",
            "Filing Systems",
            "Reception Duties",
            "Correspondence",
            "Database Management",
            "Inventory Control",
            "Vendor Relations",
            "Office Procedures"
        ],
        "Advertising, Arts & Media": [
            "Content Creation",
            "Digital Media",
            "Social Media",
            "Creative Direction",
            "Brand Strategy",
            "Media Planning",
            "Event Management",
            "Graphic Design",
            "Copywriting",
            "Marketing Communications",
            "Video Production",
            "Photography",
            "Art Direction",
            "Campaign Development",
            "Media Buying",
            "Public Relations",
            "Creative Strategy",
            "Digital Advertising",
            "Brand Development",
            "Content Strategy"
        ],
        "Banking & Financial Services": [
            "Financial Analysis",
            "Risk Management",
            "Investment Banking",
            "Wealth Management",
            "Financial Planning",
            "Credit Analysis",
            "Treasury Operations",
            "Compliance",
            "Portfolio Management",
            "Financial Services",
            "Loan Processing",
            "Asset Management",
            "Financial Advisory",
            "Banking Operations",
            "Mortgage Services",
            "Corporate Banking",
            "Retail Banking",
            "Financial Products",
            "Investment Strategy",
            "Financial Consulting"
        ],
        "Call Centre & Customer Service": [
            "Customer Support",
            "Client Relations",
            "Technical Support",
            "Customer Experience",
            "Service Delivery",
            "Quality Assurance",
            "Team Leadership",
            "Problem Resolution",
            "Customer Success",
            "Service Operations",
            "Call Handling",
            "Customer Retention",
            "Service Excellence",
            "Customer Satisfaction",
            "Help Desk",
            "Customer Care",
            "Service Management",
            "Customer Engagement",
            "Service Quality",
            "Customer Communication"
        ],
        "CEO & General Management": [
            "Strategic Planning",
            "Business Development",
            "Executive Leadership",
            "Operations Management",
            "Corporate Strategy",
            "Change Management",
            "Performance Management",
            "Business Transformation",
            "Corporate Governance",
            "Strategic Initiatives",
            "Organizational Leadership",
            "Business Strategy",
            "Executive Management",
            "Corporate Development",
            "Strategic Direction",
            "Business Operations",
            "Leadership Development",
            "Corporate Planning",
            "Business Growth",
            "Executive Decision Making"
        ],
        "Community Services & Development": [
            "Social Work",
            "Community Development",
            "Program Management",
            "Case Management",
            "Social Services",
            "Community Outreach",
            "Youth Services",
            "Family Services",
            "Community Engagement",
            "Social Impact",
            "Community Programs",
            "Social Support",
            "Community Relations",
            "Social Advocacy",
            "Community Planning",
            "Social Policy",
            "Community Resources",
            "Social Intervention",
            "Community Building",
            "Social Welfare"
        ],
        "Construction": [
            "Project Management",
            "Site Management",
            "Construction Planning",
            "Building Management",
            "Contract Management",
            "Construction Safety",
            "Quality Control",
            "Construction Supervision",
            "Building Services",
            "Construction Operations",
            "Site Supervision",
            "Construction Coordination",
            "Building Inspection",
            "Construction Scheduling",
            "Site Safety",
            "Construction Documentation",
            "Building Codes",
            "Construction Estimation",
            "Site Planning",
            "Construction Technology"
        ],
        "Consulting & Strategy": [
            "Business Strategy",
            "Management Consulting",
            "Strategic Planning",
            "Business Analysis",
            "Change Management",
            "Process Improvement",
            "Digital Transformation",
            "Strategy Development",
            "Business Advisory",
            "Performance Optimization",
            "Strategic Consulting",
            "Business Transformation",
            "Organizational Development",
            "Strategic Implementation",
            "Business Process",
            "Strategic Analysis",
            "Consulting Services",
            "Business Solutions",
            "Strategic Leadership",
            "Business Intelligence"
        ],
        "Design & Architecture": [
            "Architectural Design",
            "Interior Design",
            "UI/UX Design",
            "Graphic Design",
            "Product Design",
            "Space Planning",
            "Design Management",
            "Creative Direction",
            "Visual Design",
            "Design Strategy",
            "Landscape Design",
            "Industrial Design",
            "Web Design",
            "Design Development",
            "Design Coordination",
            "Design Documentation",
            "Design Concepts",
            "Design Implementation",
            "Design Innovation",
            "Design Technology"
        ],
        "Education & Training": [
            "Curriculum Development",
            "Teaching",
            "Educational Technology",
            "Student Services",
            "Academic Administration",
            "Educational Leadership",
            "Training & Development",
            "Learning Management",
            "Educational Research",
            "Student Support",
            "Instructional Design",
            "Educational Planning",
            "Academic Programs",
            "Student Assessment",
            "Educational Innovation",
            "Learning Systems",
            "Educational Operations",
            "Academic Services",
            "Educational Strategy",
            "Student Development"
        ],
        "Engineering": [
            "Project Management",
            "Technical Design",
            "System Architecture",
            "Quality Assurance",
            "Process Improvement",
            "Technical Documentation",
            "Engineering Design",
            "Product Development",
            "Technical Analysis",
            "Engineering Management",
            "System Engineering",
            "Technical Planning",
            "Engineering Operations",
            "Technical Solutions",
            "Engineering Coordination",
            "Technical Innovation",
            "Engineering Services",
            "Technical Support",
            "Engineering Strategy",
            "Technical Implementation"
        ],
        "Farming, Animals & Conservation": [
            "Agricultural Management",
            "Farm Operations",
            "Conservation",
            "Animal Care",
            "Sustainable Agriculture",
            "Crop Management",
            "Livestock Management",
            "Environmental Conservation",
            "Agricultural Technology",
            "Farm Planning",
            "Animal Welfare",
            "Agricultural Production",
            "Farm Administration",
            "Agricultural Research",
            "Environmental Protection",
            "Agricultural Innovation",
            "Farm Safety",
            "Agricultural Services",
            "Conservation Planning",
            "Agricultural Development"
        ],
        "Government & Defence": [
            "Public Policy",
            "Government Relations",
            "Defense Operations",
            "Public Administration",
            "Policy Development",
            "Government Services",
            "Defense Strategy",
            "Public Sector Management",
            "Government Compliance",
            "Defense Planning",
            "Public Affairs",
            "Government Operations",
            "Defense Management",
            "Public Service",
            "Government Programs",
            "Defense Technology",
            "Public Safety",
            "Government Strategy",
            "Defense Coordination",
            "Public Management"
        ],
        "Healthcare & Medical": [
            "Patient Care",
            "Medical Administration",
            "Healthcare Management",
            "Clinical Operations",
            "Medical Records",
            "Healthcare Technology",
            "Medical Coding",
            "Healthcare Compliance",
            "Patient Services",
            "Healthcare Analytics",
            "Clinical Support",
            "Medical Services",
            "Healthcare Operations",
            "Patient Safety",
            "Medical Documentation",
            "Healthcare Quality",
            "Clinical Management",
            "Medical Technology",
            "Healthcare Planning",
            "Patient Management"
        ],
        "Hospitality & Tourism": [
            "Hotel Management",
            "Customer Service",
            "Event Planning",
            "Tourism Management",
            "Food Service",
            "Guest Relations",
            "Hospitality Operations",
            "Travel Services",
            "Restaurant Management",
            "Tourism Development",
            "Hotel Operations",
            "Guest Services",
            "Hospitality Marketing",
            "Tourism Planning",
            "Event Coordination",
            "Hospitality Technology",
            "Travel Planning",
            "Tourism Services",
            "Hospitality Sales",
            "Guest Experience"
        ],
        "Human Resources & Recruitment": [
            "Talent Acquisition",
            "Employee Relations",
            "HR Management",
            "Recruitment",
            "Training & Development",
            "Performance Management",
            "HR Operations",
            "Workforce Planning",
            "Employee Engagement",
            "HR Strategy",
            "Talent Management",
            "HR Administration",
            "Employee Development",
            "HR Analytics",
            "Compensation Management",
            "HR Technology",
            "Employee Services",
            "HR Compliance",
            "Organizational Development",
            "HR Consulting"
        ],
        "Information & Communication Technology": [
            "Software Development",
            "Web Development",
            "Database Management",
            "Cloud Computing",
            "Cybersecurity",
            "Network Administration",
            "System Administration",
            "IT Support",
            "DevOps",
            "UI/UX Design",
            "Mobile Development",
            "Data Analytics",
            "IT Management",
            "Software Engineering",
            "System Integration",
            "IT Operations",
            "Technology Consulting",
            "Digital Solutions",
            "IT Strategy",
            "Technology Innovation"
        ],
        "Insurance & Superannuation": [
            "Risk Assessment",
            "Claims Management",
            "Insurance Operations",
            "Underwriting",
            "Policy Management",
            "Insurance Compliance",
            "Actuarial Analysis",
            "Insurance Technology",
            "Customer Service",
            "Insurance Products",
            "Risk Management",
            "Insurance Sales",
            "Claims Processing",
            "Insurance Administration",
            "Policy Development",
            "Insurance Analytics",
            "Risk Analysis",
            "Insurance Planning",
            "Insurance Strategy",
            "Insurance Services"
        ],
        "Legal": [
            "Legal Research",
            "Contract Law",
            "Corporate Law",
            "Legal Compliance",
            "Legal Documentation",
            "Legal Analysis",
            "Legal Operations",
            "Legal Technology",
            "Legal Services",
            "Legal Strategy",
            "Legal Administration",
            "Legal Support",
            "Legal Writing",
            "Legal Management",
            "Legal Consulting",
            "Legal Planning",
            "Legal Coordination",
            "Legal Innovation",
            "Legal Development",
            "Legal Implementation"
        ],
        "Manufacturing, Transport & Logistics": [
            "Supply Chain Management",
            "Logistics Operations",
            "Manufacturing Operations",
            "Transport Management",
            "Inventory Management",
            "Quality Control",
            "Production Planning",
            "Warehouse Management",
            "Distribution Management",
            "Operations Management",
            "Logistics Coordination",
            "Manufacturing Planning",
            "Supply Chain Optimization",
            "Transport Coordination",
            "Logistics Technology",
            "Manufacturing Technology",
            "Operations Planning",
            "Logistics Strategy",
            "Manufacturing Strategy",
            "Supply Chain Strategy"
        ],
        "Marketing & Communications": [
            "Digital Marketing",
            "Social Media",
            "Content Creation",
            "Brand Management",
            "SEO",
            "Email Marketing",
            "Market Research",
            "Public Relations",
            "Advertising",
            "Marketing Strategy",
            "Marketing Analytics",
            "Campaign Management",
            "Marketing Operations",
            "Brand Strategy",
            "Marketing Technology",
            "Marketing Communications",
            "Marketing Planning",
            "Marketing Innovation",
            "Marketing Development",
            "Marketing Coordination"
        ],
        "Mining, Resources & Energy": [
            "Resource Management",
            "Mining Operations",
            "Energy Management",
            "Environmental Compliance",
            "Safety Management",
            "Resource Planning",
            "Mining Technology",
            "Energy Operations",
            "Resource Development",
            "Mining Safety",
            "Energy Planning",
            "Resource Coordination",
            "Mining Planning",
            "Energy Technology",
            "Resource Strategy",
            "Mining Strategy",
            "Energy Strategy",
            "Resource Innovation",
            "Mining Innovation",
            "Energy Innovation"
        ],
        "Real Estate & Property": [
            "Property Management",
            "Real Estate Sales",
            "Property Development",
            "Real Estate Marketing",
            "Property Investment",
            "Real Estate Operations",
            "Property Valuation",
            "Real Estate Technology",
            "Property Services",
            "Real Estate Strategy",
            "Property Planning",
            "Real Estate Administration",
            "Property Coordination",
            "Real Estate Development",
            "Property Analysis",
            "Real Estate Consulting",
            "Property Innovation",
            "Real Estate Innovation",
            "Property Strategy",
            "Real Estate Planning"
        ],
        "Retail & Consumer Products": [
            "Retail Management",
            "Merchandising",
            "Customer Service",
            "Inventory Management",
            "Sales Operations",
            "Retail Technology",
            "Store Operations",
            "Retail Planning",
            "Customer Experience",
            "Retail Strategy",
            "Retail Sales",
            "Retail Administration",
            "Retail Coordination",
            "Retail Development",
            "Retail Analytics",
            "Retail Innovation",
            "Retail Services",
            "Retail Operations",
            "Retail Marketing",
            "Retail Consulting"
        ],
        "Sales": [
            "Business Development",
            "Account Management",
            "Sales Strategy",
            "Client Relations",
            "Negotiation",
            "Sales Operations",
            "Customer Acquisition",
            "Sales Analytics",
            "Team Leadership",
            "Revenue Growth",
            "Sales Management",
            "Sales Planning",
            "Sales Coordination",
            "Sales Development",
            "Sales Technology",
            "Sales Innovation",
            "Sales Services",
            "Sales Administration",
            "Sales Consulting",
            "Sales Implementation"
        ],
        "Science & Technology": [
            "Research & Development",
            "Scientific Analysis",
            "Laboratory Management",
            "Data Analysis",
            "Technical Research",
            "Scientific Operations",
            "Research Management",
            "Technical Analysis",
            "Scientific Technology",
            "Research Strategy",
            "Scientific Planning",
            "Research Coordination",
            "Scientific Development",
            "Research Innovation",
            "Scientific Services",
            "Research Administration",
            "Scientific Consulting",
            "Research Implementation",
            "Scientific Strategy",
            "Research Technology"
        ],
        "Sport & Recreation": [
            "Sports Management",
            "Fitness Training",
            "Recreation Planning",
            "Sports Coaching",
            "Facility Management",
            "Sports Operations",
            "Recreation Services",
            "Sports Development",
            "Fitness Management",
            "Sports Strategy",
            "Recreation Management",
            "Sports Administration",
            "Recreation Coordination",
            "Sports Technology",
            "Recreation Technology",
            "Sports Innovation",
            "Recreation Innovation",
            "Sports Services",
            "Recreation Development",
            "Sports Planning"
        ],
        "Trades & Services": [
            "Technical Services",
            "Maintenance Operations",
            "Service Management",
            "Technical Support",
            "Service Operations",
            "Technical Maintenance",
            "Service Planning",
            "Technical Operations",
            "Service Delivery",
            "Technical Strategy",
            "Service Strategy",
            "Technical Planning",
            "Service Coordination",
            "Technical Coordination",
            "Service Technology",
            "Technical Innovation",
            "Service Innovation",
            "Technical Development",
            "Service Development",
            "Technical Administration"
        ]
    }
};

const CONFIG = Object.freeze(config);
export default CONFIG;
